---
abstract: 'Adds disassemble support via B::Concise to Devel::Trepan'
author:
  - 'Rocky Bernstein <rocky@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.32
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Trepan-Disassemble
provides:
  Devel::Trepan::CmdProcessor::Command::Disassemble:
    file: lib/Devel/Trepan/CmdProcessor/Command/Disassemble.pm
    version: 0
  Devel::Trepan::Disassemble:
    file: lib/Devel/Trepan/Disassemble.pm
    version: 1.9
recommends:
  Pod::Text::Color: 2.06
requires:
  B::Concise: 0
  Devel::Callsite: 0.06
  Devel::Trepan: 0.49
  Getopt::Long: 0
  perl: 5.008
  rlib: 0.02
resources:
  bugtracker: https://github.com/rocky/Perl-Devel-Trepan-Disassemble/issues
  license: http://www.gnu.org/licenses/old-licenses/gpl-1.0.txt
  repository: http://github.com/rocky/Perl-Devel-Trepan-Disassemble
version: 1.9
