---
abstract: 'Adds disassemble support via B::Concise to Devel::Trepan'
author:
  - 'Rocky Bernstein <rocky@cpan.org>'
build_requires:
  Data::Dumper: '0'
  Syntax::Highlight::Perl::Improved: '1.01'
  Test::Simple: '0.81'
  rlib: '0.02'
configure_requires:
  Module::Build: '0.32'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150001'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-Trepan-Disassemble
provides:
  Devel::Trepan::CmdProcessor::Command::Disassemble:
    file: lib/Devel/Trepan/CmdProcessor/Command/Disassemble.pm
  Devel::Trepan::Disassemble:
    file: lib/Devel/Trepan/Disassemble.pm
    version: v2.0.1
recommends:
  Pod::Text::Color: '2.06'
requires:
  B::Concise: '0'
  Devel::Callsite: '0.08'
  Devel::Trepan: '0.71'
  Getopt::Long: '0'
  perl: '5.008008'
  rlib: '0.02'
resources:
  bugtracker: https://github.com/rocky/Perl-Devel-Trepan-Disassemble/issues
  license: http://opensource.org/licenses/gpl-license.php
  repository: http://github.com/rocky/Perl-Devel-Trepan-Disassemble
version: v2.0.1
